### ISSUE TITLE
Can you add sender data in send tx?

### ISSUE THREAD

**Issue by buildernode** [EggPool/NyzoCli#1]
The tool is good. 
If sender data and send max in the send tx feature, that will be nice.
Thank you bro.

**Comment by EggPool** [comment]
Thanks,

sender data is supported. Just updated the readme to make it clearer.
Added "send max" to the roadmap, thanks for the suggest!

**Comment by buildernode** [comment]
Thank you. 
Looking for updating.

**Comment by Non12e** [comment]
when update?

**Comment by EggPool** [comment]
Send full balance is now supported, just specify "-1" as amount.

**Comment by buildernode** [comment]
> Send full balance is now supported, just specify "-1" as amount.
Error: no such option: -1

**Comment by EggPool** [comment]
Thanks,

Just pushed bugfix and doc.
